"""empty message

Revision ID: ea9c7cbb5723
Revises: None
Create Date: 2016-06-25 21:33:50.441346

"""

# revision identifiers, used by Alembic.
revision = 'ea9c7cbb5723'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_hechos_geom', 'hechos', ['geom'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    ### end Alembic commands ###
